name: pastillero_inteligente
description: "Pastillero Inteligente - Control Medico by VitaCode"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  flutter_iconly: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  dio: ^5.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true